---
# tasks file for helloworld

- name: install helloworld by copying 
  copy:
    src: helloworld.js
    dest: /home/ec2-user/helloworld.js
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld  


- name: copy the start script
  copy:
    src: helloworld.conf
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644

- name: starting the service 
  service:
    name: helloworld
    state: started
